### ISSUE TITLE
`process: zlib` causes ReferenceError: require is not defined

### ISSUE THREAD

**Issue by trejkaz** [kaitai-io/kaitai_struct_webide#68]
I had written a structure file where one of the structures had deflate-compressed data in it.

      ytmp_payload_zlib:
        seq:
          - id: data
            size-eos: true
            process: zlib

When I open this in the Web IDE, I get an error:

    Call stack: undefined ReferenceError: require is not defined

If I comment out `process: zlib`, the file can be parsed with no problems.

**Comment by GreyCat** [comment]
This is strange, I thought it was resolved some time ago, i.e. see #33 and #46 and #47...

**Comment by trejkaz** [comment]
Is there a way to tell whether the update from #46 is actually live on the public site?

**Comment by Barracuda72** [comment]
Just run into this bug and was surprised that it's still not fixed

**Comment by generalmimon** [comment]
> was surprised that it's still not fixed

In fact, it's already fixed, but just in the development ("unstable") version of the Web IDE: https://ide.kaitai.io/devel/

@GreyCat, can you please close this issue?

**Comment by GreyCat** [comment]
Thanks for clarifying. Proceeding with closing.
